### PR TITLE
feat(adapters): add interport ccip

### PR DESCRIPTION
**Pull request by astroKo**

### CODE REVIEW

**Comment by vrtnd** [comment]
we have separate listing for all circle transactions

**Comment by astroKo** [comment]
> we have separate listing for all circle transactions

Could you specify the place where we can add circle transactions tracking?

**Comment by vrtnd** [comment]
> > we have separate listing for all circle transactions
> 
> Could you specify the place where we can add circle transactions tracking?

we have circle listed as separate bridge so its volume is counted already

**Comment by astroKo** [comment]
> > > we have separate listing for all circle transactions
> > 
> > 
> > Could you specify the place where we can add circle transactions tracking?
> 
> we have circle listed as separate bridge so its volume is counted already

Okay, thanks! Can we proceed with merging the CCIP now?

**Pull request merged**
